import type { Metadata } from 'next'
import './globals.css'
import Header from 'src/components/Header/Header'
import { poppins } from 'src/styles/font'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element => {
  return (
    <html lang='en' className={poppins.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
