import type { Metadata } from 'next'
import '@/styles/globals.css'
import Header from 'src/components/Header/Header'
import { avant_Grade } from '@/styles/font'
import ThemeProvider from '@/components/Themes/Theme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element => {
  return (
    <html lang='en' className={avant_Grade.className} suppressHydrationWarning>
      <body>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout
