import type { Metadata } from 'next'
import './globals.css'
import Header from 'src/components/Header/Header'
import { avant_Grade } from '@/styles/font'
import ThemeProvider from '@/app/theme'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const LocaleLayout = async ({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>): Promise<JSX.Element> => {
  const messages = await getMessages()
  return (
    <html lang={locale} className={avant_Grade.className} suppressHydrationWarning>
      <body>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <NextIntlClientProvider messages={messages}>
            <Header />
            {children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

export default LocaleLayout
