import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header/Header'
import ThemeProvider from '@/app/theme'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { montserrat } from '@/fonts/font'
import styles from '@/styles/styles'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = async ({ children, params: { locale } }: Readonly<I_Props_RootLayout>): Promise<JSX.Element> => {
  const messages = await getMessages()
  return (
    <html lang={locale} className={`${montserrat.className} ${styles.textSize}`} suppressHydrationWarning>
      <body>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <NextIntlClientProvider messages={messages}>
            <Header />
            <main>{children}</main>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout
